'use strict';

export const NONE = 'NONE';
export const CHECK_IMAGE = 'CHECK_IMAGE';
export const CHECK_IMAGE_PENDING = 'CHECK_IMAGE_PENDING';
export const CHECK_IMAGE_FULFILLED = 'CHECK_IMAGE_FULFILLED';
export const CHECK_IMAGE_REJECTED = 'CHECK_IMAGE_REJECTED';

export const ADD_USER_STATUS = 'ADD_USER_STATUS';
export const ADD_USER_STATUS_PENDING = 'ADD_USER_STATUS_PENDING';
export const ADD_USER_STATUS_FULFILLED = 'ADD_USER_STATUS_FULFILLED';
export const ADD_USER_STATUS_REJECTED = 'ADD_USER_STATUS_REJECTED';

export const CREATE_PIN = 'CREATE_PIN';
export const CREATE_PIN_PENDING = 'CREATE_PIN_PENDING';
export const CREATE_PIN_FULFILLED = 'CREATE_PIN_FULFILLED';
export const CREATE_PIN_REJECTED = 'CREATE_PIN_REJECTED';


export const REMOVE_USER_STATUS = 'REMOVE_USER_STATUS';
export const REMOVE_USER_STATUS_FULFILLED = 'REMOVE_USER_STATUS_FULFILLED';
export const REMOVE_USER_STATUS_REJECTED = 'REMOVE_USER_STATUS_REJECTED';

export const FETCH_ALL_PINS = 'FETCH_ALL_PINS';
export const FETCH_ALL_PINS_FAILED = 'FETCH_ALL_PINS_FAILED';
export const REQUEST_ALL_PINS = 'REQUEST_ALL_PINS';

export const ADD_USER_PINS = 'ADD_USER_PINS';
export const ADD_USER_PINS_FAILED = 'ADD_USER_PINS_FAILED';

export const UPDATE_LIKED = 'UPDATE_LIKED';
export const UPDATE_LIKED_FAILED = 'UPDATE_LIKED_FAILED';

export const REMOVE_USER_PIN = 'REMOVE_USER_PIN';
export const REMOVE_USER_PIN_FAILED = 'REMOVE_USER_PIN_FAILED';
